CREATE DATABASE test;

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  access VARCHAR(20) NOT NULL,
  username VARCHAR(40) NOT NULL UNIQUE, 
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  bio VARCHAR(400) NOT NULL DEFAULT '',
  question VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE articles(
  id SERIAL PRIMARY KEY UNIQUE,
  createdBy VARCHAR(40) NOT NULL,
  statusCheck VARCHAR (20) NOT NULL,
  content VARCHAR(400) NOT NULL DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
